<?php

use Drupal\Core\Datetime\DrupalDateTime;
use Drupal\datetime\Plugin\Field\FieldType\DateTimeItemInterface;

//use Drupal\user\Entity\Role;
use Drupal\user\Entity\User;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Entity\EntityStorageInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Theme\ThemeManagerInterface;
use Drupal\webform\Entity\WebformSubmission;
use Drupal\views\ViewExecutableFactory;

/*
 * Implement hook_help.
 * Test code is written to help page
 */
function club_test_help($route_name, RouteMatchInterface $route_match) {

  if ($route_name == 'help.page.club_test') {

  $field = 'field_schedule_date';
  $entity_type_id = 'club_schedule';
  
  $entity_definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  $definition = $update_manager->getFieldStorageDefinition($field, $entity_type_id);


   kint($definition);
   die;
  }
}
 
/*
    $update_manager = \Drupal::service('entity.definition_update_manager');
  
    $entity_id = 'webform_submission';
    $fields = [
      'entity_id_comment',
      'entity_id_smart_date_rule',
    ];
   
    foreach ($fields as $field) {
      // Load the field storage definition for the field to be uninstalled.
      $definition = $update_manager->getFieldStorageDefinition($field, $entity_id);

      // Uninstall the field storage definition.
      if ($definition) {
        $update_manager->uninstallFieldStorageDefinition($definition);
      }
      echo '<br>The base field <strong>' . $field . '</strong> was uninstalled from ' . $entity_id;
    }
   
    die;
*/