name: 'Bikeclub Announcements'
description: 'Provides Announcement content type. Announcements are published for a scheduled period of time and displayed on the home page.'
type: 'Content type'
recipes:
  - bikeclub_content_type_base
config:
  strict: false
  actions:
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        - 'create announcement content'
        - 'delete any announcement content'
        - 'edit any announcement content'
        - 'use text format basic_html'
        - 'use text format summary_fields'
    pathauto.pattern.content:
      simpleConfigUpdate:
        bundles:
          announcement: announcement