name: 'Bikeclub Content type base'
description: 'Provides field storage, text editors, and basic page content type.'
type: 'Content field'
recipes:
  - core/recipes/feedback_contact_form
  - bikeclub_media
install:
  - ckeditor5
  - contextual
  - editor
  - layout_builder
  - node
  - options
  - taxonomy
  - user
  # Contrib.
  - add_content_by_bundle 
  - conditional_fields  
  - contact_storage
  - entity_reference_revisions
  - field_group
  - layout_builder_admin_theme
  - layout_paragraphs
  - paragraphs
  - pathauto
  - quick_node_clone
  - scheduler
  - tac_lite
  # Custom
  - bikeclub
config:
  strict: false
  import:
    contact: '*'
    contact_storage: '*'
    node:
      # Import config which is imported by the Standard profile,
      # exclude field.storage.node.body. Include optional views.
      - core.entity_view_mode.node.full
      - core.entity_view_mode.node.rss
      - core.entity_view_mode.node.teaser
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
      - views.view.archive
      - views.view.content_recent
      - views.view.content
      - views.view.frontpage
    pathauto: '*'
    quick_node_clone: '*'
    scheduler:
      - views.view.scheduler_scheduled_content
  # Media is installed so include Media persmissions here.
  actions:
    node.settings:
      simpleConfigUpdate:
        use_admin_theme: true
    scheduler.settings:
      simple_config_update:
        hide_seconds: true
        log: false
    user.role.anonymous:
      grantPermissions:
        - 'access user contact forms'
    user.role.authenticated:
      grantPermissions:
        - 'access user contact forms'
        - 'use text format basic_html'
        - 'use text format summary_fields'
