_core:
  default_config_hash: Ccm_9FhbmFTBDLZfm7YBrCDTC5mhvXeqNcYSZAeIJJE
favicon:
  path: ''
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: false
  node_user_picture: true
logo:
  path: 'public://header.svg'
  use_default: false
scheme: light
